# Change these first
owner: qover-me # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Qover website
    url: https://www.qover.com
  - name: Bike insurance API
    url: $BIKE_API
  - name: Motor insurance API
    url: $IAB_API
  - name: Claims API
    url: $CLAIMS_API
  - name: EyeWear insurance API
    url: $EYEWEAR_API
  - name: Home insurance API
    url: $TENANT_API

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Qover
  introTitle: "**Qover** monitor and status page."
  introMessage: We continuously monitor Qover.com and all its services. If there are any performance or service interruptions, an update will be posted here.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
