# Change these first
owner: qover-me # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Qover website
    url: https://www.qover.com
  - name: Bike insurance API
    url: $BIKE_API
  - name: Motor insurance API
    url: $IAB_API
  - name: Claims API
    url: $CLAIMS_API
  - name: EyeWear insurance API
    url: $EYEWEAR_API
  - name: Home insurance API
    url: $TENANT_API
  - name: Policy API
    url: $POLICY_API

status-website:
  cname: status.qover.com
  logoUrl: https://raw.githubusercontent.com/qover-me/upptime/master/assets/logo-qover.svg
  name: ""
  favicon: https://raw.githubusercontent.com/qover-me/upptime/master/assets/favicon_q.png
  introTitle: "**Qover** monitor and status page."
  introMessage: We continuously monitor Qover.com and all its services. If there are any performance or service interruptions, an update will be posted here.
  navbar:
    - title: Status
      href: /
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
